spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/gabriel_db
    username: root
    password: gabrielroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

