spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/gabriel_db
    username: root
    password: gabrielroot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect


